[project]
name = "mcp-starter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=2.11.2",
    "python-dotenv>=1.1.1",
    "pypandoc>=1.14",
    "requests>=2.31.0",
]
