[project]
name = "word-to-pdf-mcp"
version = "0.1.0"
description = "MCP server for validation and Word-to-PDF conversion tools"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.11.2",
    "python-dotenv>=1.1.1",
    "pypandoc>=1.14",
    "requests>=2.31.0",
]
